name: simplenotes

services:
  app:
    build: .
    hostname: simplenotes
    ports:
      - "8081:80"
    environment:
      NODE_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 80
      DB_HOST: simplenotesdb
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASS: apppass
    depends_on:
      db:
        condition: service_healthy
    networks:
      - simplenotes

  db:
    image: mysql:latest
    hostname: simplenotesdb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - simplenotes

volumes:
  db_data:

networks:
  simplenotes:
    driver: bridge
